/**
 * Destination modal photo hero manifest (prototype).
 * Keyed by destination id — same ids used in destinations.config.js and the modal.
 * Missing entries or failed image loads fall back to the dark editorial header.
 */
window.DESTINATION_IMAGE_MANIFEST = {
  "st-barts": {
    src: "/images/destinations/st-barts-hero.jpg",
    alt: "Saint Barth - Vue panoramique - Octobre 2009",
    credit: "Starus",
    sourceUrl: "https://commons.wikimedia.org/wiki/File%3ASaint%20Barth%20-%20Vue%20panoramique%20-%20Octobre%202009.jpg",
    license: "CC BY-SA 3.0",
    source: "Wikimedia Commons",
    objectPosition: "center center",
    queryUsed: "Saint Barthelemy aerial",
    wikimediaFile: "Saint Barth - Vue panoramique - Octobre 2009.jpg",
    reviewed: true,
  },
  "turks-caicos": {
    src: "/images/destinations/turks-caicos-hero.jpg",
    alt: "Grace Bay, Providenciales - Turks and Caicos Islands. An old shot on my first DSLR. Using the kit lens and probably hand held, this was the only shot I kept of that sunset. This beach and the Atlantic Ocean's calm crystal clear water make this a very special place. One of the best beaches in the world.",
    credit: "Jason Boldero",
    sourceUrl: "https://commons.wikimedia.org/wiki/File%3ASunset%20in%20Grace%20Bay%2C%20Turks%20and%20Caicos%20Islands.jpg",
    license: "CC BY 2.0",
    source: "Wikimedia Commons",
    objectPosition: "center 40%",
    queryUsed: "Grace Bay Turks Caicos",
    wikimediaFile: "Sunset in Grace Bay, Turks and Caicos Islands.jpg",
    reviewed: true,
  },
  anguilla: {
    src: "/images/destinations/anguilla-hero.jpg",
    alt: "An aerial view of the western portion of the island of Anguilla. The Blowing Point ferry terminal is visible in the lower right, as are (right to left) Shaddick Point, Rendezvous Bay, Cove Bay, and Maundays Bay.",
    credit: "Roy Googin",
    sourceUrl: "https://commons.wikimedia.org/wiki/File%3AAnguilla-aerial%20view%20western%20portion.jpg",
    license: "CC BY 3.0",
    source: "Wikimedia Commons",
    objectPosition: "center 35%",
    queryUsed: "Anguilla island aerial",
    wikimediaFile: "Anguilla-aerial view western portion.jpg",
    reviewed: true,
  },
  mustique: {
    src: "/images/destinations/mustique-hero.jpg",
    alt: "Image of Lagoon Beach, Mustique Island, and the Caribbean Sea. Photographed on the path to Gelliceaux Beach, looking north",
    credit: "Alecstatic",
    sourceUrl: "https://commons.wikimedia.org/wiki/File%3ALagoon%20Beach%2C%20Mustique.jpg",
    license: "CC BY-SA 4.0",
    source: "Wikimedia Commons",
    objectPosition: "center 40%",
    queryUsed: "Mustique island",
    wikimediaFile: "Lagoon Beach, Mustique.jpg",
    reviewed: true,
  },
  "harbour-island": {
    src: "/images/destinations/harbour-island-hero.jpg",
    alt: "Aerial shot of gentle sea waves on a pink sand beach creates a tranquil scene.",
    credit: "Mikhail Nilov",
    sourceUrl: "https://www.pexels.com/photo/ocean-waves-on-brown-sand-9400980/",
    photographer: "Mikhail Nilov",
    photographerUrl: "https://www.pexels.com/@mikhail-nilov",
    license: "Pexels License",
    source: "Pexels",
    objectPosition: "center 35%",
    queryUsed: "Harbour Island pink sand Bahamas",
    pexelsPhotoId: 9400980,
    reviewed: false,
  },
  mykonos: {
    src: "/images/destinations/mykonos-hero.jpg",
    alt: "Beautiful view of the famous windmills on Mykonos island's coastline with clear blue skies and sea.",
    credit: "Stéphane Tendon",
    sourceUrl: "https://www.pexels.com/photo/windmills-on-the-mykonos-island-in-greece-seen-from-the-sea-16738967/",
    photographer: "Stéphane Tendon",
    photographerUrl: "https://www.pexels.com/@stephane-tendon-65970413",
    license: "Pexels License",
    source: "Pexels",
    objectPosition: "center 40%",
    queryUsed: "Mykonos windmills Greece",
    pexelsPhotoId: 16738967,
    reviewed: false,
  },
  ibiza: {
    src: "/images/destinations/ibiza-hero.jpg",
    alt: "Scenic view of historic white-washed buildings in Ibiza, Balearic Islands, Spain.",
    credit: "Raymond Petrik",
    sourceUrl: "https://www.pexels.com/photo/historic-architecture-in-ibiza-s-old-town-29041770/",
    photographer: "Raymond Petrik",
    photographerUrl: "https://www.pexels.com/@raymond-petrik-1448389535",
    license: "Pexels License",
    source: "Pexels",
    objectPosition: "center center",
    queryUsed: "Ibiza old town Dalt Vila",
    pexelsPhotoId: 29041770,
    reviewed: false,
  },
  "st-tropez": {
    src: "/images/destinations/st-tropez-hero.jpg",
    alt: "Discover the vibrant coastal town of Saint Tropez with its iconic harbor and old town charm.",
    credit: "Helena Jankovičová Kováčová",
    sourceUrl: "https://www.pexels.com/photo/old-town-of-saint-tropez-see-from-hill-6931306/",
    photographer: "Helena Jankovičová Kováčová",
    photographerUrl: "https://www.pexels.com/@helen1",
    license: "Pexels License",
    source: "Pexels",
    objectPosition: "center 40%",
    queryUsed: "Saint Tropez harbor France",
    pexelsPhotoId: 6931306,
    reviewed: false,
  },
  "sardinia-olbia": {
    src: "/images/destinations/sardinia-olbia-hero.jpg",
    alt: "Stunning aerial view of turquoise waters and rugged coastline in La Maddalena Archipelago, Sardinia.",
    credit: "Kaio Murilo",
    sourceUrl: "https://www.pexels.com/photo/aerial-view-of-la-maddalena-archipelago-sardinia-29489683/",
    photographer: "Kaio Murilo",
    photographerUrl: "https://www.pexels.com/@kaio-murilo-236638494",
    license: "Pexels License",
    source: "Pexels",
    objectPosition: "center 35%",
    queryUsed: "Costa Smeralda Sardinia aerial",
    pexelsPhotoId: 29489683,
    reviewed: false,
  },
  aspen: {
    src: "/images/destinations/aspen-hero.jpg",
    alt: "Breathtaking winter landscape of snow-covered Maroon Bells with vibrant autumn foliage in Aspen, Colorado.",
    credit: "Jeff Wiles",
    sourceUrl: "https://www.pexels.com/photo/scenic-winter-view-of-maroon-bells-in-aspen-35599275/",
    photographer: "Jeff Wiles",
    photographerUrl: "https://www.pexels.com/@jeff-wiles-2155751648",
    license: "Pexels License",
    source: "Pexels",
    objectPosition: "center center",
    queryUsed: "Aspen Colorado mountains",
    pexelsPhotoId: 35599275,
    reviewed: false,
  },
  courchevel: {
    src: "/images/destinations/courchevel-hero.jpg",
    alt: "Snow-covered mountains at Courchevel sign, perfect for winter sports and scenic views.",
    credit: "MetaX Studios",
    sourceUrl: "https://www.pexels.com/photo/stunning-winter-view-of-courchevel-mountains-37044653/",
    photographer: "MetaX Studios",
    photographerUrl: "https://www.pexels.com/@metaxstudios",
    license: "Pexels License",
    source: "Pexels",
    objectPosition: "center 35%",
    queryUsed: "Courchevel ski resort France",
    pexelsPhotoId: 37044653,
    reviewed: false,
  },
  "st-moritz": {
    src: "/images/destinations/st-moritz-hero.jpg",
    alt: "Beautiful lake and mountain landscape in St. Moritz, Switzerland under clear blue sky.",
    credit: "Jean-Paul Wettstein",
    sourceUrl: "https://www.pexels.com/photo/stunning-lake-view-in-swiss-alps-summer-landscape-37650646/",
    photographer: "Jean-Paul Wettstein",
    photographerUrl: "https://www.pexels.com/@jean-paul-wettstein-677916508",
    license: "Pexels License",
    source: "Pexels",
    objectPosition: "center 35%",
    queryUsed: "St Moritz lake Switzerland",
    pexelsPhotoId: 37650646,
    reviewed: false,
  },
  "jackson-hole": {
    src: "/images/destinations/jackson-hole-hero.jpg",
    alt: "Northwestern Wyoming's 45 mile long, north-south oriented Teton Range is dominated by Archean-aged igneous and metamorphic rocks. The flat-floored valley on its eastern side is Jackson Hole Valley, where the equivalent Archean rocks are at a considerable depth underground. The Teton Range and Jackson Hole Valley are separated by a major normal fault called the Teton Fault, which has experienced about 30,000 feet worth of offset. The tallest mountain at the center of the above photograph is Grand Teton itself, which peaks out at 13,770 feet above sea level.",
    credit: "James St. John",
    sourceUrl: "https://commons.wikimedia.org/wiki/File%3AGrand%20Teton%20(Teton%20Range%2C%20Grand%20Teton%20National%20Park%2C%20Wyoming%2C%20USA)%20(19771495898).jpg",
    license: "CC BY 2.0",
    source: "Wikimedia Commons",
    objectPosition: "center 35%",
    queryUsed: "Grand Teton Jackson Hole",
    wikimediaFile: "Grand Teton (Teton Range, Grand Teton National Park, Wyoming, USA) (19771495898).jpg",
    reviewed: true,
  },
  hamptons: {
    src: "/images/destinations/hamptons-hero.jpg",
    alt: "Atlantic shoreline and dunes near the Hamptons, Long Island",
    credit: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Coopers_Beach_Hamptons.jpg",
    license: "CC BY-SA 3.0",
    objectPosition: "center 40%",
  },
  nantucket: {
    src: "/images/destinations/nantucket-hero.jpg",
    alt: "Scenic view of Brant Point Lighthouse with cloudy sky in Nantucket, Massachusetts.",
    credit: "David Kanigan",
    sourceUrl: "https://www.pexels.com/photo/photo-of-a-lighthouse-13859561/",
    photographer: "David Kanigan",
    photographerUrl: "https://www.pexels.com/@david-kanigan-239927285",
    license: "Pexels License",
    source: "Pexels",
    objectPosition: "center center",
    queryUsed: "Nantucket harbor Massachusetts",
    pexelsPhotoId: 13859561,
    reviewed: false,
  },
  "marthas-vineyard": {
    src: "/images/destinations/marthas-vineyard-hero.jpg",
    alt: "Gay Head Aquinnah Clay Cliffs and Lighthouse Martha's Vineyard Overlook Vineyard Sound Elizabeth Islands",
    credit: "EgorovaSvetlana",
    sourceUrl: "https://commons.wikimedia.org/wiki/File%3AGay%20Head%20Aquinnah%20clay%20Cliffs%20Lighthouse%20Marthas%20Vineyard%20Overlook%20Elizabeth%20Islands.jpg",
    license: "CC BY-SA 4.0",
    source: "Wikimedia Commons",
    objectPosition: "center center",
    queryUsed: "Aquinnah cliffs Martha Vineyard",
    wikimediaFile: "Gay Head Aquinnah clay Cliffs Lighthouse Marthas Vineyard Overlook Elizabeth Islands.jpg",
    reviewed: true,
  },
  "palm-beach": {
    src: "/images/destinations/palm-beach-hero.jpg",
    alt: "Lake Worth lagoon - part of the Intracoastal Waterway, West Palm Beach, Florida",
    credit: "David Broad",
    sourceUrl: "https://commons.wikimedia.org/wiki/File%3ALake%20Worth%20lagoon%20-%20part%20of%20the%20Intracoastal%20Waterway%2C%20West%20Palm%20Beach%2C%20Florida%20-%20panoramio%20(1).jpg",
    license: "CC BY 3.0",
    source: "Wikimedia Commons",
    objectPosition: "center 40%",
    queryUsed: "Lake Worth lagoon Palm Beach",
    wikimediaFile: "Lake Worth lagoon - part of the Intracoastal Waterway, West Palm Beach, Florida - panoramio (1).jpg",
    reviewed: true,
  },
  tulum: {
    src: "/images/destinations/tulum-hero.jpg",
    alt: "Explore the stunning Mayan ruins of Tulum against a clear blue sky.",
    credit: "Ibrahim-Can DURAN",
    sourceUrl: "https://www.pexels.com/photo/ancient-mayan-ruins-in-tulum-mexico-31456573/",
    photographer: "Ibrahim-Can DURAN",
    photographerUrl: "https://www.pexels.com/@ibrahim-can-duran-562239220",
    license: "Pexels License",
    source: "Pexels",
    objectPosition: "center center",
    queryUsed: "Tulum Mayan ruins beach",
    pexelsPhotoId: 31456573,
    reviewed: false,
  },
  "cabo-san-lucas": {
    src: "/images/destinations/cabo-san-lucas-hero.jpg",
    alt: "Stunning view of El Arco rock formation, Cabo San Lucas, surrounded by the sea under a blue sky.",
    credit: "Josué Rodríguez",
    sourceUrl: "https://www.pexels.com/photo/scenic-view-of-el-arco-at-cabo-san-lucas-37939891/",
    photographer: "Josué Rodríguez",
    photographerUrl: "https://www.pexels.com/@roodzn",
    license: "Pexels License",
    source: "Pexels",
    objectPosition: "center center",
    queryUsed: "El Arco Cabo San Lucas",
    pexelsPhotoId: 37939891,
    reviewed: false,
  },
  comporta: {
    src: "/images/destinations/comporta-hero.jpg",
    alt: "A barragem do Feiticeiro é uma obra de engenharia hidroeléctrica portuguesa construída para represar o rio Sabor, no distrito de Bragança, região de Trás-os-Montes. Características Técnicas Características Hidrológicas Área da Bacia Hidrográfica – 3491 Km² Caudal de cheia – 6400 m³/s Período de retorno – 5000 anos Características da Albufeira Área inundada ao NPA – 181 ha Nível de máxima cheia (NMC) – 138 m Nível mínimo de exploração (NmE) – 130 m Descarregador de Cheias Localização – central Tipo de controlo – comportas Tipo de descarregador – Lâmina livre dividido em 4 vãos de 16m Cota da crista da soleira – 127 m Desenvolvimento da soleira – 4x16 m Caudal máximo descarregado – 5000 m³/s Dissipação de energia – Roller Bucket Descarga de fundo Localização – estrutura da barragem Tipo – através da barragem/muro lateral direito do descarregador de cheias Secção da conduta – 1,25 m x (2-4) m Caudal máximo – 51.5 m³/s Controlo a montante – comporta vagão – (1.25m x 2.0m) Controlo a jusante – comporta vagão – (1.25m x 2.0m) Energias de Portugal vendeu a barragem a um consórcio francês em dezembro de 2019. &lt;a href=\" https://pt.wikipedia.org/wiki/Barragem_do_Feiticeiro \" rel=\"noreferrer nofollow\"&gt;pt.wikipedia.org/wiki/Barragem_do_Feiticeiro&lt;/a&gt;",
    credit: "Vitor Oliveira from Torres Vedras, PORTUGAL",
    sourceUrl: "https://commons.wikimedia.org/wiki/File%3ABarragem%20do%20Feiticeiro%20-%20Portugal%20%F0%9F%87%B5%F0%9F%87%B9%20(54493453088).jpg",
    license: "CC BY-SA 2.0",
    source: "Wikimedia Commons",
    objectPosition: "center center",
    queryUsed: "Comporta aerial",
    wikimediaFile: "Barragem do Feiticeiro - Portugal 🇵🇹 (54493453088).jpg",
    reviewed: true,
  },
  barbados: {
    src: "/images/destinations/barbados-hero.jpg",
    alt: "Idyllic beach scene in Bridgetown, Barbados with clear skies and turquoise sea.",
    credit: "Neil Marshall",
    sourceUrl: "https://www.pexels.com/photo/photo-of-beach-during-summer-14250687/",
    photographer: "Neil Marshall",
    photographerUrl: "https://www.pexels.com/@neil-marshall-307186966",
    license: "Pexels License",
    source: "Pexels",
    objectPosition: "center 40%",
    queryUsed: "Barbados coastline aerial",
    pexelsPhotoId: 14250687,
    reviewed: false,
  },
  antigua: {
    src: "/images/destinations/antigua-hero.jpg",
    alt: "Vibrant cruise ships docked in the scenic harbor of Antigua, a popular Caribbean destination.",
    credit: "Duren Williams",
    sourceUrl: "https://www.pexels.com/photo/white-cruise-ship-on-sea-under-white-clouds-and-blue-sky-10656994/",
    photographer: "Duren Williams",
    photographerUrl: "https://www.pexels.com/@duren-williams-29414623",
    license: "Pexels License",
    source: "Pexels",
    objectPosition: "center 40%",
    queryUsed: "Antigua English Harbour",
    pexelsPhotoId: 10656994,
    reviewed: false,
  },
  nassau: {
    src: "/images/destinations/nassau-hero.jpg",
    alt: "Stunning ocean and villa view in Nassau, Bahamas, featuring vibrant turquoise waters and lush palm trees.",
    credit: "ACkats Films",
    sourceUrl: "https://www.pexels.com/photo/nassau-bahamas-28443536/",
    photographer: "ACkats Films",
    photographerUrl: "https://www.pexels.com/@ackats-films-1759538370",
    license: "Pexels License",
    source: "Pexels",
    objectPosition: "center 40%",
    queryUsed: "Nassau Bahamas aerial",
    pexelsPhotoId: 28443536,
    reviewed: false,
  },
  exuma: {
    src: "/images/destinations/exuma-hero.jpg",
    alt: "Flug von Great &lt;a href=\" https://de.wikipedia.org/wiki/Exuma_(Bahamas) \" rel=\"nofollow\"&gt;Exuma&lt;/a&gt; nach Nassau: Blick auf Great Exuma mit George Town und Stocking Island.",
    credit: "Rüdiger Stehn from Kiel, Deutschland",
    sourceUrl: "https://commons.wikimedia.org/wiki/File%3ABahamas%201989%20(589)%20Great%20Exuma%20(25497769082).jpg",
    license: "CC BY-SA 2.0",
    source: "Wikimedia Commons",
    objectPosition: "center center",
    queryUsed: "Stocking Island Exuma aerial",
    wikimediaFile: "Bahamas 1989 (589) Great Exuma (25497769082).jpg",
    reviewed: true,
  },
  "casa-de-campo": {
    src: "/images/destinations/casa-de-campo-hero.jpg",
    alt: "Stunning coastal view from La Romana, Dominican Republic. Perfect summer getaway.",
    credit: "Conal McGuirk",
    sourceUrl: "https://www.pexels.com/photo/motorboats-on-tropical-sea-shore-19813799/",
    photographer: "Conal McGuirk",
    photographerUrl: "https://www.pexels.com/@conal-mcguirk-2418200",
    license: "Pexels License",
    source: "Pexels",
    objectPosition: "center 40%",
    queryUsed: "La Romana Dominican Republic coast",
    pexelsPhotoId: 19813799,
    reviewed: false,
  },
  "capri-naples": {
    src: "/images/destinations/capri-naples-hero.jpg",
    alt: "Stunning view of the Faraglioni rock formations off the coast of Capri, Italy, under a clear blue sky.",
    credit: "Lauren Cuddy",
    sourceUrl: "https://www.pexels.com/photo/view-of-sea-stacks-on-the-coast-of-capri-near-naples-italy-20523049/",
    photographer: "Lauren Cuddy",
    photographerUrl: "https://www.pexels.com/@laurencuddy",
    license: "Pexels License",
    source: "Pexels",
    objectPosition: "center 40%",
    queryUsed: "Capri Faraglioni rocks",
    pexelsPhotoId: 20523049,
    reviewed: false,
  },
  "amalfi-salerno": {
    src: "/images/destinations/amalfi-salerno-hero.jpg",
    alt: "A breathtaking aerial view of Positano's colorful houses on cliffs by the Tyrrhenian Sea under a cloudy sky.",
    credit: "Alain Garcia",
    sourceUrl: "https://www.pexels.com/photo/drone-shot-of-the-amalfi-coast-in-italy-19900429/",
    photographer: "Alain Garcia",
    photographerUrl: "https://www.pexels.com/@shotbyadrone",
    license: "Pexels License",
    source: "Pexels",
    objectPosition: "center 35%",
    queryUsed: "Amalfi Coast Positano aerial",
    pexelsPhotoId: 19900429,
    reviewed: false,
  },
  mallorca: {
    src: "/images/destinations/mallorca-hero.jpg",
    alt: "The lighthouse of Cap de Formentor was erected between 1857 and 1863. It is located at 210 m above sea level and has a nominal range of 21 nautical miles (approx. 39 km). The light characteristic is 4 white flashes every 20 seconds.",
    credit: "Isiwal",
    sourceUrl: "https://commons.wikimedia.org/wiki/File%3AMallorca%20Cap%20de%20Formentor%20Faro.jpg",
    license: "CC BY-SA 3.0",
    source: "Wikimedia Commons",
    objectPosition: "center center",
    queryUsed: "Cap de Formentor Mallorca",
    wikimediaFile: "Mallorca Cap de Formentor Faro.jpg",
    reviewed: true,
  },
  "sicily-catania": {
    src: "/images/destinations/sicily-catania-hero.jpg",
    alt: "Explore the awe-inspiring ruins of the Ancient Theatre of Taormina, Sicily with Mount Etna in the background.",
    credit: "Reinhard Bruckner",
    sourceUrl: "https://www.pexels.com/photo/ancient-theatre-of-taormina-4563289/",
    photographer: "Reinhard Bruckner",
    photographerUrl: "https://www.pexels.com/@bruggi",
    license: "Pexels License",
    source: "Pexels",
    objectPosition: "center center",
    queryUsed: "Taormina Sicily coast",
    pexelsPhotoId: 4563289,
    reviewed: false,
  },
  santorini: {
    src: "/images/destinations/santorini-hero.jpg",
    alt: "Captivating landscape of Oia, Santorini showcasing white architecture and blue domes under a clear sky.",
    credit: "Federico Abis",
    sourceUrl: "https://www.pexels.com/photo/caldera-seen-from-santorini-17919743/",
    photographer: "Federico Abis",
    photographerUrl: "https://www.pexels.com/@federicoabisphotography",
    license: "Pexels License",
    source: "Pexels",
    objectPosition: "center center",
    queryUsed: "Santorini Oia caldera",
    pexelsPhotoId: 17919743,
    reviewed: false,
  },
  verbier: {
    src: "/images/destinations/verbier-hero.jpg",
    alt: "Le Châble is a village in Bagnes, Valais, Switzerland, below the ski resort of Verbier.",
    credit: "Patrick Nouhailler from Genève, Suisse",
    sourceUrl: "https://commons.wikimedia.org/wiki/File%3ALe%20Ch%C3%A2ble%20(33017810655).jpg",
    license: "CC BY-SA 2.0",
    source: "Wikimedia Commons",
    objectPosition: "center center",
    queryUsed: "Verbier ski resort Switzerland",
    wikimediaFile: "Le Châble (33017810655).jpg",
    reviewed: true,
  },
  "megeve-chamonix": {
    src: "/images/destinations/megeve-chamonix-hero.jpg",
    alt: "Cable car ascending Aiguille du Midi with Mont Blanc as a backdrop in winter, Chamonix.",
    credit: "Ercan Evcimen",
    sourceUrl: "https://www.pexels.com/photo/aiguille-du-midi-cable-car-in-chamonix-30514665/",
    photographer: "Ercan Evcimen",
    photographerUrl: "https://www.pexels.com/@ercan-evcimen-626365917",
    license: "Pexels License",
    source: "Pexels",
    objectPosition: "center center",
    queryUsed: "Chamonix Mont Blanc aerial",
    pexelsPhotoId: 30514665,
    reviewed: false,
  },
  whistler: {
    src: "/images/destinations/whistler-hero.jpg",
    alt: "Whistler Mountain and Garibaldi Provincial Park from Seventh Heaven on Blackcomb Mountain",
    credit: "Ruth Hartnup from Vancouver, Canada",
    sourceUrl: "https://commons.wikimedia.org/wiki/File%3AWhistler%20Mountain%20and%20Garibaldi%20Provincial%20Park%20from%20Seventh%20Heaven%20on%20Blackcomb%20Mountain%20(40214637654).jpg",
    license: "CC BY 2.0",
    source: "Wikimedia Commons",
    objectPosition: "center 35%",
    queryUsed: "Whistler Blackcomb mountains",
    wikimediaFile: "Whistler Mountain and Garibaldi Provincial Park from Seventh Heaven on Blackcomb Mountain (40214637654).jpg",
    reviewed: true,
  },
  "cape-cod": {
    src: "/images/destinations/cape-cod-hero.jpg",
    alt: "Dramatic sunset sky over Cape Cod lighthouse in Provincetown, Massachusetts, creating a serene coastal scene.",
    credit: "Phil Evenden",
    sourceUrl: "https://www.pexels.com/photo/cape-cod-lighthouse-under-vibrant-sunset-sky-34530629/",
    photographer: "Phil Evenden",
    photographerUrl: "https://www.pexels.com/@philevenphotos",
    license: "Pexels License",
    source: "Pexels",
    objectPosition: "center 40%",
    queryUsed: "Cape Cod Chatham lighthouse",
    pexelsPhotoId: 34530629,
    reviewed: false,
  },
  "block-island": {
    src: "/images/destinations/block-island-hero.jpg",
    alt: "A breathtaking view of Mohegan Bluffs in New Shoreham, Rhode Island, with ocean waves and a clear blue sky.",
    credit: "Mohan Nannapaneni",
    sourceUrl: "https://www.pexels.com/photo/green-grass-on-cliff-coast-13297739/",
    photographer: "Mohan Nannapaneni",
    photographerUrl: "https://www.pexels.com/@mnannapaneni",
    license: "Pexels License",
    source: "Pexels",
    objectPosition: "center 40%",
    queryUsed: "Block Island Mohegan Bluffs",
    pexelsPhotoId: 13297739,
    reviewed: false,
  },
  "hilton-head": {
    src: "/images/destinations/hilton-head-hero.jpg",
    alt: "Palmetto-lined path leading toward the beach at Hilton Head Island",
    credit: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Hilton_Head_Island_Beach.jpg",
    license: "CC BY 2.0",
    objectPosition: "center 35%",
  },
  charleston: {
    src: "/images/destinations/charleston-hero.jpg",
    alt: "Drone shot of Arthur Ravenel Jr. Bridge over the Cooper River in Charleston, showcasing a scenic view with surrounding greenery.",
    credit: "Jaxon Matthew Willis",
    sourceUrl: "https://www.pexels.com/photo/aerial-view-of-a-long-bridge-and-ship-on-a-body-of-water-12485587/",
    photographer: "Jaxon Matthew Willis",
    photographerUrl: "https://www.pexels.com/@jaxon-matthew-willis-55957128",
    license: "Pexels License",
    source: "Pexels",
    objectPosition: "center 35%",
    queryUsed: "Charleston Rainbow Row aerial",
    pexelsPhotoId: 12485587,
    reviewed: false,
  },
  "sun-valley": {
    src: "/images/destinations/sun-valley-hero.jpg",
    alt: "This is a photo of Bald Mountain, as seen from Sun Valley, Idaho. The ski town of Sun Valley is the focus of Sun Valley Magazine.",
    credit: "Rickmouser45",
    sourceUrl: "https://commons.wikimedia.org/wiki/File%3ABald%20Mountain%20in%20Sun%20Valley%2C%20Idaho.jpg",
    license: "CC BY-SA 4.0",
    source: "Wikimedia Commons",
    objectPosition: "center 35%",
    queryUsed: "Bald Mountain Sun Valley Idaho",
    wikimediaFile: "Bald Mountain in Sun Valley, Idaho.jpg",
    reviewed: true,
  },
  napa: {
    src: "/images/destinations/napa-hero.jpg",
    alt: "Vineyard stretching across Napa Valley, California, under a clear blue sky.",
    credit: "Gabriel Tovar",
    sourceUrl: "https://www.pexels.com/photo/scenic-vineyard-in-california-s-napa-valley-35227785/",
    photographer: "Gabriel Tovar",
    photographerUrl: "https://www.pexels.com/@gabriel-tovar-2156003919",
    license: "Pexels License",
    source: "Pexels",
    objectPosition: "center center",
    queryUsed: "Napa Valley vineyards aerial",
    pexelsPhotoId: 35227785,
    reviewed: false,
  },
  "santa-fe": {
    src: "/images/destinations/santa-fe-hero.jpg",
    alt: "Santa Fe is the capital of the United States state of New Mexico. It is the fourth-largest city in the state and is the seat of Santa Fe County. Santa Fe is also the oldest capital city in the United States. Santa Fe (meaning “holy faith” in Spanish) had a population of 69,204 in 2012.The city’s full name when founded was La Villa Real de la Santa Fe de San Francisco de Asís (“The Royal Town of the Holy Faith of St. Francis of Assisi”). Don Juan de Oñate led the first effort to colonize the region in 1598, establishing Santa Fe de Nuevo México as a province of New Spain. In 1610, he made it the capital of the province, which it has almost constantly remained, making it the oldest state capital in the United States. The Spanish laid out the city according to the “Laws of the Indies”, town planning rules and ordinances which had been established in 1573 by King Philip II. The fundamental principle was that the town be laid out around a central plaza. On its north side was the Palace of the Governors, while on the east was the church that later became the Cathedral Basilica of Saint Francis of Assisi. The city is well known as a center for arts that reflect the multicultural character of the city; it has been designated as a UNESCO Creative City in Design, Crafts and Folk Art. The city and the surrounding areas have a high concentration of artists. They have come over the decades to capture the natural beauty of the landscape, the flora and the fauna. One of the most well-known New Mexico–based artists was Georgia O'Keeffe, who lived for a time in Santa Fe, but primarily in Abiquiu, a small village about 50 mi (80 km) away. By an ordinance passed in 1957, new and rebuilt buildings, especially those in designated historic districts, must exhibit a Spanish Territorial or Pueblo style of architecture, with flat roofs and other features suggestive of the area's traditional adobe construction. en.wikipedia.org/wiki/Santa_Fe,_New_Mexico en.wikipedia.org/wiki/Wikipedia:Text_of_Creative_Commons_...",
    credit: "Ken Lund",
    sourceUrl: "https://commons.wikimedia.org/wiki/File%3ARoute%2066%2C%20Santa%20Fe%2C%20New%20Mexico%20(cropped).jpg",
    license: "CC BY-SA 2.0",
    source: "Wikimedia Commons",
    objectPosition: "center center",
    queryUsed: "Santa Fe Plaza adobe New Mexico",
    wikimediaFile: "Route 66, Santa Fe, New Mexico (cropped).jpg",
    reviewed: true,
  },
  "coronado-san-diego": {
    src: "/images/destinations/coronado-san-diego-hero.jpg",
    alt: "Stunning San Diego skyline featuring Coronado Bridge and glowing city lights reflecting in the bay at night.",
    credit: "Soly Moses",
    sourceUrl: "https://www.pexels.com/photo/san-diego-skyline-with-coronado-bridge-at-night-37026470/",
    photographer: "Soly Moses",
    photographerUrl: "https://www.pexels.com/@solyartphotos",
    license: "Pexels License",
    source: "Pexels",
    objectPosition: "center 35%",
    queryUsed: "Coronado Bridge San Diego",
    pexelsPhotoId: 37026470,
    reviewed: false,
  },
  "destin-30a": {
    src: "/images/destinations/destin-30a-hero.jpg",
    alt: "Golden sunrise over Destin Beach with charming seaside cottages and serene sands.",
    credit: "Esteban Carriazo",
    sourceUrl: "https://www.pexels.com/photo/scenic-sunrise-at-destin-beach-florida-32942419/",
    photographer: "Esteban Carriazo",
    photographerUrl: "https://www.pexels.com/@esteban-carriazo-2153373740",
    license: "Pexels License",
    source: "Pexels",
    objectPosition: "center 40%",
    queryUsed: "Destin Florida emerald coast",
    pexelsPhotoId: 32942419,
    reviewed: false,
  },
  "puerto-vallarta": {
    src: "/images/destinations/puerto-vallarta-hero.jpg",
    alt: "Los Arcos (Puerto Vallarta)",
    credit: "daryl_mitchell",
    sourceUrl: "https://commons.wikimedia.org/wiki/File%3ALos%20Arcos%202.jpg",
    license: "CC BY-SA 2.0",
    source: "Wikimedia Commons",
    objectPosition: "center center",
    queryUsed: "Los Arcos Puerto Vallarta",
    wikimediaFile: "Los Arcos 2.jpg",
    reviewed: true,
  },
  "puerto-escondido": {
    src: "/images/destinations/puerto-escondido-hero.jpg",
    alt: "Explore the rugged coastline with rocks and waves at Puerto Escondido, Mexico.",
    credit: "Dante Muñoz",
    sourceUrl: "https://www.pexels.com/photo/a-beach-with-rocks-and-water-in-the-background-15941841/",
    photographer: "Dante Muñoz",
    photographerUrl: "https://www.pexels.com/@dantemunozphoto",
    license: "Pexels License",
    source: "Pexels",
    objectPosition: "center 40%",
    queryUsed: "Puerto Escondido beach Oaxaca",
    pexelsPhotoId: 15941841,
    reviewed: false,
  },
  phuket: {
    src: "/images/destinations/phuket-hero.jpg",
    alt: "อุทยานแห่งชาติอ่าวพังงา",
    credit: "Vyacheslav Argenberg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File%3ALimestone%20karst%20landscape%20of%20Phang%20Nga%20Bay%2C%20Thailand.jpg",
    license: "CC BY 4.0",
    source: "Wikimedia Commons",
    objectPosition: "center center",
    queryUsed: "Phang Nga Bay Thailand karst",
    wikimediaFile: "Limestone karst landscape of Phang Nga Bay, Thailand.jpg",
    reviewed: true,
  },
  maldives: {
    src: "/images/destinations/maldives-hero.jpg",
    alt: "A breathtaking aerial view of overwater bungalows and pristine beaches in Kaafu Atoll, Maldives.",
    credit: "Asad Photo Maldives",
    sourceUrl: "https://www.pexels.com/photo/aerial-view-of-body-of-water-9215858/",
    photographer: "Asad Photo Maldives",
    photographerUrl: "https://www.pexels.com/@asadphoto",
    license: "Pexels License",
    source: "Pexels",
    objectPosition: "center 35%",
    queryUsed: "Maldives overwater bungalows aerial",
    pexelsPhotoId: 9215858,
    reviewed: false,
  },
  bali: {
    src: "/images/destinations/bali-hero.jpg",
    alt: "Stunning aerial view of Tegallalang Rice Terraces in Ubud, Bali, showcasing lush greenery and traditional huts.",
    credit: "Tom Fisk",
    sourceUrl: "https://www.pexels.com/photo/aerial-view-of-tegallalang-rice-terraces-bali-36716820/",
    photographer: "Tom Fisk",
    photographerUrl: "https://www.pexels.com/@tomfisk",
    license: "Pexels License",
    source: "Pexels",
    objectPosition: "center 35%",
    queryUsed: "Bali rice terraces Tegallalang",
    pexelsPhotoId: 36716820,
    reviewed: false,
  },
  "koh-samui": {
    src: "/images/destinations/koh-samui-hero.jpg",
    alt: "Explore the stunning coastal view of Koh Samui with lush greenery and bright blue sea.",
    credit: "foad niestat",
    sourceUrl: "https://www.pexels.com/photo/scenic-koh-samui-coastline-in-thailand-30852253/",
    photographer: "foad niestat",
    photographerUrl: "https://www.pexels.com/@foad-niestat-2645615",
    license: "Pexels License",
    source: "Pexels",
    objectPosition: "center 40%",
    queryUsed: "Koh Samui Thailand aerial",
    pexelsPhotoId: 30852253,
    reviewed: false,
  },
  "dubai-private": {
    src: "/images/destinations/dubai-private-hero.jpg",
    alt: "Stunning view of Dubai's skyline at twilight featuring the iconic Burj Khalifa.",
    credit: "Dreamer  Dude",
    sourceUrl: "https://www.pexels.com/photo/outstanding-cityscape-of-dubai-across-sea-at-dusk-18341554/",
    photographer: "Dreamer  Dude",
    photographerUrl: "https://www.pexels.com/@dreamer-dude-724231353",
    license: "Pexels License",
    source: "Pexels",
    objectPosition: "center 35%",
    queryUsed: "Dubai skyline Burj Khalifa",
    pexelsPhotoId: 18341554,
    reviewed: false,
  },
  "punta-del-este": {
    src: "/images/destinations/punta-del-este-hero.jpg",
    alt: "A serene sunset view over Punta del Este beach, capturing the natural beauty of Uruguay's coastline.",
    credit: "Pedro  Slinger",
    sourceUrl: "https://www.pexels.com/photo/city-buildings-near-the-shore-11838869/",
    photographer: "Pedro  Slinger",
    photographerUrl: "https://www.pexels.com/@pedrosk",
    license: "Pexels License",
    source: "Pexels",
    objectPosition: "center 40%",
    queryUsed: "Punta del Este La Mano sculpture",
    pexelsPhotoId: 11838869,
    reviewed: false,
  },
  marrakech: {
    src: "/images/destinations/marrakech-hero.jpg",
    alt: "A bustling scene at Jemaa el-Fnaa square in Marrakech with local snake charmers and tourists",
    credit: "Diego F. Parra",
    sourceUrl: "https://www.pexels.com/photo/jemaa-el-fnaa-square-in-marrakech-25489943/",
    photographer: "Diego F. Parra",
    photographerUrl: "https://www.pexels.com/@diego-f-parra-33199",
    license: "Pexels License",
    source: "Pexels",
    objectPosition: "center center",
    queryUsed: "Marrakech medina aerial",
    pexelsPhotoId: 25489943,
    reviewed: false,
  },
};
