export const DESTINATIONS = [
  {
    id: 'st-barts',
    name: 'St. Barthélemy',
    region: 'French Caribbean',
    icao: ['TFFJ'],
    lat: 17.9047,
    lng: -62.8442,
    season: ['year-round'],
    priority: 'tier-1',
  },
  {
    id: 'turks-caicos',
    name: 'Turks & Caicos (Providenciales)',
    region: 'Caribbean',
    icao: ['MBPV'],
    lat: 21.7736,
    lng: -72.2659,
    season: ['year-round'],
    priority: 'tier-1',
  },
  {
    id: 'anguilla',
    name: 'Anguilla',
    region: 'British Caribbean',
    icao: ['TQPF'],
    lat: 18.2049,
    lng: -63.0551,
    season: ['year-round'],
    priority: 'tier-2',
  },
  {
    id: 'mustique',
    name: 'Mustique',
    region: 'Caribbean',
    icao: ['TVSM'],
    lat: 12.8881,
    lng: -61.1801,
    season: ['year-round'],
    priority: 'tier-2',
  },
  {
    id: 'harbour-island',
    name: "Harbour Island (North Eleuthera)",
    region: 'Bahamas',
    icao: ['MYEH'],
    lat: 25.4747,
    lng: -76.6835,
    season: ['year-round'],
    priority: 'tier-2',
  },
  {
    id: 'mykonos',
    name: 'Mykonos',
    region: 'Greek Islands',
    icao: ['LGMK'],
    lat: 37.4351,
    lng: 25.3481,
    season: ['summer'],
    priority: 'tier-1',
  },
  {
    id: 'ibiza',
    name: 'Ibiza',
    region: 'Balearic Islands',
    icao: ['LEIB'],
    lat: 38.8729,
    lng: 1.3731,
    season: ['summer'],
    priority: 'tier-1',
  },
  {
    id: 'st-tropez',
    name: 'St. Tropez (La Mole)',
    region: "Côte d'Azur",
    icao: ['LFTZ'],
    lat: 43.2055,
    lng: 6.482,
    season: ['summer'],
    priority: 'tier-1',
  },
  {
    id: 'sardinia-olbia',
    name: 'Sardinia / Olbia',
    region: 'Sardinia',
    icao: ['LIEO'],
    lat: 40.8987,
    lng: 9.5176,
    season: ['summer'],
    priority: 'tier-2',
  },
  {
    id: 'aspen',
    name: 'Aspen',
    region: 'Colorado Rockies',
    icao: ['KASE'],
    lat: 39.2232,
    lng: -106.8687,
    season: ['winter', 'summer'],
    priority: 'tier-1',
  },
  {
    id: 'courchevel',
    name: 'Courchevel',
    region: 'French Alps',
    icao: ['LFLJ'],
    lat: 45.3967,
    lng: 6.6347,
    season: ['winter'],
    priority: 'tier-1',
  },
  {
    id: 'st-moritz',
    name: 'St. Moritz (Samedan)',
    region: 'Swiss Alps',
    icao: ['LSZS'],
    lat: 46.534,
    lng: 9.8842,
    season: ['winter'],
    priority: 'tier-2',
  },
  {
    id: 'jackson-hole',
    name: 'Jackson Hole',
    region: 'Wyoming',
    icao: ['KJAC', 'KDIJ'],
    lat: 43.6073,
    lng: -110.7377,
    season: ['winter', 'summer'],
    priority: 'tier-1',
  },
  {
    id: 'hamptons',
    name: 'Hamptons',
    region: 'New York',
    icao: ['KJPX', 'KFOK'],
    lat: 40.954,
    lng: -72.253,
    season: ['summer'],
    priority: 'tier-1',
  },
  {
    id: 'nantucket',
    name: 'Nantucket',
    region: 'Massachusetts',
    icao: ['KACK'],
    lat: 41.2531,
    lng: -70.0601,
    season: ['summer'],
    priority: 'tier-1',
  },
  {
    id: 'marthas-vineyard',
    name: "Martha's Vineyard",
    region: 'Massachusetts',
    icao: ['KMVY'],
    lat: 41.3893,
    lng: -70.6143,
    season: ['summer'],
    priority: 'tier-2',
  },
  {
    id: 'palm-beach',
    name: 'Palm Beach',
    region: 'Florida',
    icao: ['KPBI'],
    lat: 26.6832,
    lng: -80.0956,
    season: ['winter'],
    priority: 'tier-1',
  },
  {
    id: 'tulum',
    name: 'Tulum',
    region: 'Riviera Maya',
    icao: ['MMTO', 'MMUN'],
    lat: 20.2114,
    lng: -87.4654,
    season: ['year-round'],
    priority: 'tier-1',
  },
  {
    id: 'cabo-san-lucas',
    name: 'Cabo San Lucas',
    region: 'Baja California Sur',
    icao: ['MMSD'],
    lat: 23.1518,
    lng: -109.7211,
    season: ['year-round'],
    priority: 'tier-1',
  },
  {
    id: 'comporta',
    name: 'Comporta (Lisbon area)',
    region: 'Portugal',
    icao: ['LPMT'],
    lat: 38.4019,
    lng: -8.5947,
    season: ['year-round'],
    priority: 'tier-1',
  },
];
