/**
 * Destination modal photo hero manifest (prototype).
 * Keyed by destination id — same ids used in destinations.config.js and the modal.
 * Missing entries or failed image loads fall back to the dark editorial header.
 */
window.DESTINATION_IMAGE_MANIFEST = {
  "st-barts": {
    src: "/images/destinations/st-barts-hero.jpg",
    alt: "Explore a vibrant Caribbean harbor with lush hills and anchored ships under a clear blue sky.",
    credit: "Arian Fernandez",
    sourceUrl: "https://www.pexels.com/photo/aerial-view-of-scenic-harbor-in-caribbean-island-34650312/",
    photographer: "Arian Fernandez",
    photographerUrl: "https://www.pexels.com/@troopper84",
    license: "Pexels License",
    source: "Pexels",
    objectPosition: "center 35%",
    queryUsed: "Caribbean island harbor aerial",
    pexelsPhotoId: 34650312,
    reviewed: false,
  },
  "turks-caicos": {
    src: "/images/destinations/turks-caicos-hero.jpg",
    alt: "A stunning aerial view of the Caribbean coastline in Carabobo, Venezuela, showcasing lush greenery and turquoise waters.",
    credit: "Hiurich G.",
    sourceUrl: "https://www.pexels.com/photo/green-trees-near-blue-sea-under-blue-sky-13831431/",
    photographer: "Hiurich G.",
    photographerUrl: "https://www.pexels.com/@hiurich",
    license: "Pexels License",
    source: "Pexels",
    objectPosition: "center 35%",
    queryUsed: "Caribbean coast",
    pexelsPhotoId: 13831431,
    reviewed: false,
  },
  anguilla: {
    src: "/images/destinations/anguilla-hero.jpg",
    alt: "Stunning aerial view of Sandy Ground Bay in Anguilla with boats and turquoise waters.",
    credit: "Juergen Striewski",
    sourceUrl: "https://www.pexels.com/photo/view-of-seacoast-with-yachts-and-sailboats-12315051/",
    photographer: "Juergen Striewski",
    photographerUrl: "https://www.pexels.com/@striewa",
    license: "Pexels License",
    source: "Pexels",
    objectPosition: "center 35%",
    queryUsed: "Anguilla island aerial",
    pexelsPhotoId: 12315051,
    reviewed: false,
  },
  mustique: {
    src: "/images/destinations/mustique-hero.jpg",
    alt: "Stunning aerial shot capturing a remote island's green landscape meeting the vast blue ocean.",
    credit: "IslandHopper X",
    sourceUrl: "https://www.pexels.com/photo/drone-photography-of-island-during-daytime-15214459/",
    photographer: "IslandHopper X",
    photographerUrl: "https://www.pexels.com/@iwashere",
    license: "Pexels License",
    source: "Pexels",
    objectPosition: "center 35%",
    queryUsed: "Grenadines island aerial",
    pexelsPhotoId: 15214459,
    reviewed: false,
  },
  "harbour-island": {
    src: "/images/destinations/harbour-island-hero.jpg",
    alt: "Aerial shot of gentle sea waves on a pink sand beach creates a tranquil scene.",
    credit: "Mikhail Nilov",
    sourceUrl: "https://www.pexels.com/photo/ocean-waves-on-brown-sand-9400980/",
    photographer: "Mikhail Nilov",
    photographerUrl: "https://www.pexels.com/@mikhail-nilov",
    license: "Pexels License",
    source: "Pexels",
    objectPosition: "center 35%",
    queryUsed: "Harbour Island pink sand Bahamas",
    pexelsPhotoId: 9400980,
    reviewed: false,
  },
  mykonos: {
    src: "/images/destinations/mykonos-hero.jpg",
    alt: "Beautiful view of the famous windmills on Mykonos island's coastline with clear blue skies and sea.",
    credit: "Stéphane Tendon",
    sourceUrl: "https://www.pexels.com/photo/windmills-on-the-mykonos-island-in-greece-seen-from-the-sea-16738967/",
    photographer: "Stéphane Tendon",
    photographerUrl: "https://www.pexels.com/@stephane-tendon-65970413",
    license: "Pexels License",
    source: "Pexels",
    objectPosition: "center 40%",
    queryUsed: "Mykonos windmills Greece",
    pexelsPhotoId: 16738967,
    reviewed: false,
  },
  ibiza: {
    src: "/images/destinations/ibiza-hero.jpg",
    alt: "Scenic view of historic white-washed buildings in Ibiza, Balearic Islands, Spain.",
    credit: "Raymond Petrik",
    sourceUrl: "https://www.pexels.com/photo/historic-architecture-in-ibiza-s-old-town-29041770/",
    photographer: "Raymond Petrik",
    photographerUrl: "https://www.pexels.com/@raymond-petrik-1448389535",
    license: "Pexels License",
    source: "Pexels",
    objectPosition: "center center",
    queryUsed: "Ibiza old town Dalt Vila",
    pexelsPhotoId: 29041770,
    reviewed: false,
  },
  "st-tropez": {
    src: "/images/destinations/st-tropez-hero.jpg",
    alt: "Discover the vibrant coastal town of Saint Tropez with its iconic harbor and old town charm.",
    credit: "Helena Jankovičová Kováčová",
    sourceUrl: "https://www.pexels.com/photo/old-town-of-saint-tropez-see-from-hill-6931306/",
    photographer: "Helena Jankovičová Kováčová",
    photographerUrl: "https://www.pexels.com/@helen1",
    license: "Pexels License",
    source: "Pexels",
    objectPosition: "center 40%",
    queryUsed: "Saint Tropez harbor France",
    pexelsPhotoId: 6931306,
    reviewed: false,
  },
  "sardinia-olbia": {
    src: "/images/destinations/sardinia-olbia-hero.jpg",
    alt: "Stunning aerial view of turquoise waters and rugged coastline in La Maddalena Archipelago, Sardinia.",
    credit: "Kaio Murilo",
    sourceUrl: "https://www.pexels.com/photo/aerial-view-of-la-maddalena-archipelago-sardinia-29489683/",
    photographer: "Kaio Murilo",
    photographerUrl: "https://www.pexels.com/@kaio-murilo-236638494",
    license: "Pexels License",
    source: "Pexels",
    objectPosition: "center 35%",
    queryUsed: "Costa Smeralda Sardinia aerial",
    pexelsPhotoId: 29489683,
    reviewed: false,
  },
  aspen: {
    src: "/images/destinations/aspen-hero.jpg",
    alt: "Breathtaking winter landscape of snow-covered Maroon Bells with vibrant autumn foliage in Aspen, Colorado.",
    credit: "Jeff Wiles",
    sourceUrl: "https://www.pexels.com/photo/scenic-winter-view-of-maroon-bells-in-aspen-35599275/",
    photographer: "Jeff Wiles",
    photographerUrl: "https://www.pexels.com/@jeff-wiles-2155751648",
    license: "Pexels License",
    source: "Pexels",
    objectPosition: "center center",
    queryUsed: "Aspen Colorado mountains",
    pexelsPhotoId: 35599275,
    reviewed: false,
  },
  courchevel: {
    src: "/images/destinations/courchevel-hero.jpg",
    alt: "Snow-covered mountains at Courchevel sign, perfect for winter sports and scenic views.",
    credit: "MetaX Studios",
    sourceUrl: "https://www.pexels.com/photo/stunning-winter-view-of-courchevel-mountains-37044653/",
    photographer: "MetaX Studios",
    photographerUrl: "https://www.pexels.com/@metaxstudios",
    license: "Pexels License",
    source: "Pexels",
    objectPosition: "center 35%",
    queryUsed: "Courchevel ski resort France",
    pexelsPhotoId: 37044653,
    reviewed: false,
  },
  "st-moritz": {
    src: "/images/destinations/st-moritz-hero.jpg",
    alt: "Beautiful lake and mountain landscape in St. Moritz, Switzerland under clear blue sky.",
    credit: "Jean-Paul Wettstein",
    sourceUrl: "https://www.pexels.com/photo/stunning-lake-view-in-swiss-alps-summer-landscape-37650646/",
    photographer: "Jean-Paul Wettstein",
    photographerUrl: "https://www.pexels.com/@jean-paul-wettstein-677916508",
    license: "Pexels License",
    source: "Pexels",
    objectPosition: "center 35%",
    queryUsed: "St Moritz lake Switzerland",
    pexelsPhotoId: 37650646,
    reviewed: false,
  },
  "jackson-hole": {
    src: "/images/destinations/jackson-hole-hero.jpg",
    alt: "Stunning aerial view of Jackson Hole with the Teton Range in the background under a clear blue sky.",
    credit: "Purniima's Photography Page",
    sourceUrl: "https://www.pexels.com/photo/panoramic-view-of-jackson-hole-and-teton-range-35401875/",
    photographer: "Purniima's Photography Page",
    photographerUrl: "https://www.pexels.com/@purniima-s-photography-page-77352719",
    license: "Pexels License",
    source: "Pexels",
    objectPosition: "center 35%",
    queryUsed: "Grand Teton Jackson Hole",
    pexelsPhotoId: 35401875,
    reviewed: false,
  },
  hamptons: {
    src: "/images/destinations/hamptons-hero.jpg",
    alt: "Atlantic shoreline and dunes near the Hamptons, Long Island",
    credit: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Coopers_Beach_Hamptons.jpg",
    license: "CC BY-SA 3.0",
    objectPosition: "center 40%",
  },
  nantucket: {
    src: "/images/destinations/nantucket-hero.jpg",
    alt: "Scenic view of Brant Point Lighthouse with cloudy sky in Nantucket, Massachusetts.",
    credit: "David Kanigan",
    sourceUrl: "https://www.pexels.com/photo/photo-of-a-lighthouse-13859561/",
    photographer: "David Kanigan",
    photographerUrl: "https://www.pexels.com/@david-kanigan-239927285",
    license: "Pexels License",
    source: "Pexels",
    objectPosition: "center center",
    queryUsed: "Nantucket harbor Massachusetts",
    pexelsPhotoId: 13859561,
    reviewed: false,
  },
  "marthas-vineyard": {
    src: "/images/destinations/marthas-vineyard-hero.jpg",
    alt: "Beautiful coastal scenery with the Aquinnah lighthouse and cliffs under a clear blue sky.",
    credit: "Phil Evenden",
    sourceUrl: "https://www.pexels.com/photo/brown-rock-formation-near-body-of-water-11482413/",
    photographer: "Phil Evenden",
    photographerUrl: "https://www.pexels.com/@philevenphotos",
    license: "Pexels License",
    source: "Pexels",
    objectPosition: "center 40%",
    queryUsed: "Aquinnah cliffs Martha Vineyard",
    pexelsPhotoId: 11482413,
    reviewed: false,
  },
  "palm-beach": {
    src: "/images/destinations/palm-beach-hero.jpg",
    alt: "Stunning aerial view of Palm Beach, NSW, with the iconic Barrenjoey Lighthouse. Perfect travel destination.",
    credit: "Onin",
    sourceUrl: "https://www.pexels.com/photo/barrenjoey-lighthouse-in-australia-26115748/",
    photographer: "Onin",
    photographerUrl: "https://www.pexels.com/@onin-416970162",
    license: "Pexels License",
    source: "Pexels",
    objectPosition: "center 35%",
    queryUsed: "Palm Beach landmark",
    pexelsPhotoId: 26115748,
    reviewed: false,
  },
  tulum: {
    src: "/images/destinations/tulum-hero.jpg",
    alt: "Explore the stunning Mayan ruins of Tulum against a clear blue sky.",
    credit: "Ibrahim-Can DURAN",
    sourceUrl: "https://www.pexels.com/photo/ancient-mayan-ruins-in-tulum-mexico-31456573/",
    photographer: "Ibrahim-Can DURAN",
    photographerUrl: "https://www.pexels.com/@ibrahim-can-duran-562239220",
    license: "Pexels License",
    source: "Pexels",
    objectPosition: "center center",
    queryUsed: "Tulum Mayan ruins beach",
    pexelsPhotoId: 31456573,
    reviewed: false,
  },
  "cabo-san-lucas": {
    src: "/images/destinations/cabo-san-lucas-hero.jpg",
    alt: "Stunning view of El Arco rock formation, Cabo San Lucas, surrounded by the sea under a blue sky.",
    credit: "Josué Rodríguez",
    sourceUrl: "https://www.pexels.com/photo/scenic-view-of-el-arco-at-cabo-san-lucas-37939891/",
    photographer: "Josué Rodríguez",
    photographerUrl: "https://www.pexels.com/@roodzn",
    license: "Pexels License",
    source: "Pexels",
    objectPosition: "center center",
    queryUsed: "El Arco Cabo San Lucas",
    pexelsPhotoId: 37939891,
    reviewed: false,
  },
  comporta: {
    src: "/images/destinations/comporta-hero.jpg",
    alt: "Peaceful sandy shore with footprints and gentle waves at sunset in Comporta, Portugal.",
    credit: "H Matias",
    sourceUrl: "https://www.pexels.com/photo/footprints-on-shore-10474698/",
    photographer: "H Matias",
    photographerUrl: "https://www.pexels.com/@h-matias-633153",
    license: "Pexels License",
    source: "Pexels",
    objectPosition: "center 40%",
    queryUsed: "Comporta Portugal beach",
    pexelsPhotoId: 10474698,
    reviewed: false,
  },
  barbados: {
    src: "/images/destinations/barbados-hero.jpg",
    alt: "Idyllic beach scene in Bridgetown, Barbados with clear skies and turquoise sea.",
    credit: "Neil Marshall",
    sourceUrl: "https://www.pexels.com/photo/photo-of-beach-during-summer-14250687/",
    photographer: "Neil Marshall",
    photographerUrl: "https://www.pexels.com/@neil-marshall-307186966",
    license: "Pexels License",
    source: "Pexels",
    objectPosition: "center 40%",
    queryUsed: "Barbados coastline aerial",
    pexelsPhotoId: 14250687,
    reviewed: false,
  },
  antigua: {
    src: "/images/destinations/antigua-hero.jpg",
    alt: "Vibrant cruise ships docked in the scenic harbor of Antigua, a popular Caribbean destination.",
    credit: "Duren Williams",
    sourceUrl: "https://www.pexels.com/photo/white-cruise-ship-on-sea-under-white-clouds-and-blue-sky-10656994/",
    photographer: "Duren Williams",
    photographerUrl: "https://www.pexels.com/@duren-williams-29414623",
    license: "Pexels License",
    source: "Pexels",
    objectPosition: "center 40%",
    queryUsed: "Antigua English Harbour",
    pexelsPhotoId: 10656994,
    reviewed: false,
  },
  nassau: {
    src: "/images/destinations/nassau-hero.jpg",
    alt: "Stunning ocean and villa view in Nassau, Bahamas, featuring vibrant turquoise waters and lush palm trees.",
    credit: "ACkats Films",
    sourceUrl: "https://www.pexels.com/photo/nassau-bahamas-28443536/",
    photographer: "ACkats Films",
    photographerUrl: "https://www.pexels.com/@ackats-films-1759538370",
    license: "Pexels License",
    source: "Pexels",
    objectPosition: "center 40%",
    queryUsed: "Nassau Bahamas aerial",
    pexelsPhotoId: 28443536,
    reviewed: false,
  },
  exuma: {
    src: "/images/destinations/exuma-hero.jpg",
    alt: "Explore the vibrant underwater world of Exuma, Bahamas with a stunning fish amidst coral and seagrass.",
    credit: "mysurrogateband",
    sourceUrl: "https://www.pexels.com/photo/underwater-paradise-fish-in-exuma-bahamas-33508336/",
    photographer: "mysurrogateband",
    photographerUrl: "https://www.pexels.com/@mysurrogateband-1076071941",
    license: "Pexels License",
    source: "Pexels",
    objectPosition: "center 40%",
    queryUsed: "Exuma harbor",
    pexelsPhotoId: 33508336,
    reviewed: false,
  },
  "casa-de-campo": {
    src: "/images/destinations/casa-de-campo-hero.jpg",
    alt: "Stunning coastal view from La Romana, Dominican Republic. Perfect summer getaway.",
    credit: "Conal McGuirk",
    sourceUrl: "https://www.pexels.com/photo/motorboats-on-tropical-sea-shore-19813799/",
    photographer: "Conal McGuirk",
    photographerUrl: "https://www.pexels.com/@conal-mcguirk-2418200",
    license: "Pexels License",
    source: "Pexels",
    objectPosition: "center 40%",
    queryUsed: "La Romana Dominican Republic coast",
    pexelsPhotoId: 19813799,
    reviewed: false,
  },
  "capri-naples": {
    src: "/images/destinations/capri-naples-hero.jpg",
    alt: "Stunning view of the Faraglioni rock formations off the coast of Capri, Italy, under a clear blue sky.",
    credit: "Lauren Cuddy",
    sourceUrl: "https://www.pexels.com/photo/view-of-sea-stacks-on-the-coast-of-capri-near-naples-italy-20523049/",
    photographer: "Lauren Cuddy",
    photographerUrl: "https://www.pexels.com/@laurencuddy",
    license: "Pexels License",
    source: "Pexels",
    objectPosition: "center 40%",
    queryUsed: "Capri Faraglioni rocks",
    pexelsPhotoId: 20523049,
    reviewed: false,
  },
  "amalfi-salerno": {
    src: "/images/destinations/amalfi-salerno-hero.jpg",
    alt: "A breathtaking aerial view of Positano's colorful houses on cliffs by the Tyrrhenian Sea under a cloudy sky.",
    credit: "Alain Garcia",
    sourceUrl: "https://www.pexels.com/photo/drone-shot-of-the-amalfi-coast-in-italy-19900429/",
    photographer: "Alain Garcia",
    photographerUrl: "https://www.pexels.com/@shotbyadrone",
    license: "Pexels License",
    source: "Pexels",
    objectPosition: "center 35%",
    queryUsed: "Amalfi Coast Positano aerial",
    pexelsPhotoId: 19900429,
    reviewed: false,
  },
  mallorca: {
    src: "/images/destinations/mallorca-hero.jpg",
    alt: "Breathtaking view of towering cliffs and deep blue sea at Cap de Formentor in Mallorca, Balearic Islands.",
    credit: "Sergei  Gussev",
    sourceUrl: "https://www.pexels.com/photo/scenic-cliffs-of-cap-de-formentor-mallorca-coast-35993135/",
    photographer: "Sergei  Gussev",
    photographerUrl: "https://www.pexels.com/@sergei",
    license: "Pexels License",
    source: "Pexels",
    objectPosition: "center 40%",
    queryUsed: "Cap de Formentor Mallorca",
    pexelsPhotoId: 35993135,
    reviewed: false,
  },
  "sicily-catania": {
    src: "/images/destinations/sicily-catania-hero.jpg",
    alt: "Explore the awe-inspiring ruins of the Ancient Theatre of Taormina, Sicily with Mount Etna in the background.",
    credit: "Reinhard Bruckner",
    sourceUrl: "https://www.pexels.com/photo/ancient-theatre-of-taormina-4563289/",
    photographer: "Reinhard Bruckner",
    photographerUrl: "https://www.pexels.com/@bruggi",
    license: "Pexels License",
    source: "Pexels",
    objectPosition: "center center",
    queryUsed: "Taormina Sicily coast",
    pexelsPhotoId: 4563289,
    reviewed: false,
  },
  santorini: {
    src: "/images/destinations/santorini-hero.jpg",
    alt: "Captivating landscape of Oia, Santorini showcasing white architecture and blue domes under a clear sky.",
    credit: "Federico Abis",
    sourceUrl: "https://www.pexels.com/photo/caldera-seen-from-santorini-17919743/",
    photographer: "Federico Abis",
    photographerUrl: "https://www.pexels.com/@federicoabisphotography",
    license: "Pexels License",
    source: "Pexels",
    objectPosition: "center center",
    queryUsed: "Santorini Oia caldera",
    pexelsPhotoId: 17919743,
    reviewed: false,
  },
  verbier: {
    src: "/images/destinations/verbier-hero.jpg",
    alt: "Scenic landscape near Verbier, Swiss Alps",
    credit: "Ryan Klaus",
    sourceUrl: "https://www.pexels.com/photo/stunning-morning-view-of-swiss-alps-in-valais-34280557/",
    photographer: "Ryan Klaus",
    photographerUrl: "https://www.pexels.com/@ryank",
    license: "Pexels License",
    source: "Pexels",
    objectPosition: "center 35%",
    queryUsed: "Verbier Valais mountains",
    pexelsPhotoId: 34280557,
    reviewed: false,
  },
  "megeve-chamonix": {
    src: "/images/destinations/megeve-chamonix-hero.jpg",
    alt: "Cable car ascending Aiguille du Midi with Mont Blanc as a backdrop in winter, Chamonix.",
    credit: "Ercan Evcimen",
    sourceUrl: "https://www.pexels.com/photo/aiguille-du-midi-cable-car-in-chamonix-30514665/",
    photographer: "Ercan Evcimen",
    photographerUrl: "https://www.pexels.com/@ercan-evcimen-626365917",
    license: "Pexels License",
    source: "Pexels",
    objectPosition: "center center",
    queryUsed: "Chamonix Mont Blanc aerial",
    pexelsPhotoId: 30514665,
    reviewed: false,
  },
  whistler: {
    src: "/images/destinations/whistler-hero.jpg",
    alt: "Rocky mountain trail with snowy peaks in Whistler, British Columbia under an overcast sky.",
    credit: "Ruqaiya Arshad",
    sourceUrl: "https://www.pexels.com/photo/view-from-a-mountain-peak-onto-rocky-mountains-15602865/",
    photographer: "Ruqaiya Arshad",
    photographerUrl: "https://www.pexels.com/@ruqaiya-arshad-399622076",
    license: "Pexels License",
    source: "Pexels",
    objectPosition: "center 35%",
    queryUsed: "Whistler Blackcomb mountains",
    pexelsPhotoId: 15602865,
    reviewed: false,
  },
  "cape-cod": {
    src: "/images/destinations/cape-cod-hero.jpg",
    alt: "Dramatic sunset sky over Cape Cod lighthouse in Provincetown, Massachusetts, creating a serene coastal scene.",
    credit: "Phil Evenden",
    sourceUrl: "https://www.pexels.com/photo/cape-cod-lighthouse-under-vibrant-sunset-sky-34530629/",
    photographer: "Phil Evenden",
    photographerUrl: "https://www.pexels.com/@philevenphotos",
    license: "Pexels License",
    source: "Pexels",
    objectPosition: "center 40%",
    queryUsed: "Cape Cod Chatham lighthouse",
    pexelsPhotoId: 34530629,
    reviewed: false,
  },
  "block-island": {
    src: "/images/destinations/block-island-hero.jpg",
    alt: "A breathtaking view of Mohegan Bluffs in New Shoreham, Rhode Island, with ocean waves and a clear blue sky.",
    credit: "Mohan Nannapaneni",
    sourceUrl: "https://www.pexels.com/photo/green-grass-on-cliff-coast-13297739/",
    photographer: "Mohan Nannapaneni",
    photographerUrl: "https://www.pexels.com/@mnannapaneni",
    license: "Pexels License",
    source: "Pexels",
    objectPosition: "center 40%",
    queryUsed: "Block Island Mohegan Bluffs",
    pexelsPhotoId: 13297739,
    reviewed: false,
  },
  "hilton-head": {
    src: "/images/destinations/hilton-head-hero.jpg",
    alt: "Palmetto-lined path leading toward the beach at Hilton Head Island",
    credit: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Hilton_Head_Island_Beach.jpg",
    license: "CC BY 2.0",
    objectPosition: "center 35%",
  },
  charleston: {
    src: "/images/destinations/charleston-hero.jpg",
    alt: "Drone shot of Arthur Ravenel Jr. Bridge over the Cooper River in Charleston, showcasing a scenic view with surrounding greenery.",
    credit: "Jaxon Matthew Willis",
    sourceUrl: "https://www.pexels.com/photo/aerial-view-of-a-long-bridge-and-ship-on-a-body-of-water-12485587/",
    photographer: "Jaxon Matthew Willis",
    photographerUrl: "https://www.pexels.com/@jaxon-matthew-willis-55957128",
    license: "Pexels License",
    source: "Pexels",
    objectPosition: "center 35%",
    queryUsed: "Charleston Rainbow Row aerial",
    pexelsPhotoId: 12485587,
    reviewed: false,
  },
  "sun-valley": {
    src: "/images/destinations/sun-valley-hero.jpg",
    alt: "Scenic view of mountains and forests under a vibrant sky in Ketchum, Idaho.",
    credit: "Brett Sayles",
    sourceUrl: "https://www.pexels.com/photo/view-of-landscape-of-mountains-1662771/",
    photographer: "Brett Sayles",
    photographerUrl: "https://www.pexels.com/@brett-sayles",
    license: "Pexels License",
    source: "Pexels",
    objectPosition: "center 35%",
    queryUsed: "Bald Mountain Sun Valley Idaho",
    pexelsPhotoId: 1662771,
    reviewed: false,
  },
  napa: {
    src: "/images/destinations/napa-hero.jpg",
    alt: "Vineyard stretching across Napa Valley, California, under a clear blue sky.",
    credit: "Gabriel Tovar",
    sourceUrl: "https://www.pexels.com/photo/scenic-vineyard-in-california-s-napa-valley-35227785/",
    photographer: "Gabriel Tovar",
    photographerUrl: "https://www.pexels.com/@gabriel-tovar-2156003919",
    license: "Pexels License",
    source: "Pexels",
    objectPosition: "center center",
    queryUsed: "Napa Valley vineyards aerial",
    pexelsPhotoId: 35227785,
    reviewed: false,
  },
  "santa-fe": {
    src: "/images/destinations/santa-fe-hero.jpg",
    alt: "A white cross on adobe building at Santa Fe, NM, silhouetted against a clear blue sky.",
    credit: "Mark Tucker",
    sourceUrl: "https://www.pexels.com/photo/cross-on-stone-building-on-blue-sky-9420221/",
    photographer: "Mark Tucker",
    photographerUrl: "https://www.pexels.com/@dxolympic",
    license: "Pexels License",
    source: "Pexels",
    objectPosition: "center center",
    queryUsed: "Santa Fe Plaza adobe New Mexico",
    pexelsPhotoId: 9420221,
    reviewed: false,
  },
  "coronado-san-diego": {
    src: "/images/destinations/coronado-san-diego-hero.jpg",
    alt: "Stunning San Diego skyline featuring Coronado Bridge and glowing city lights reflecting in the bay at night.",
    credit: "Soly Moses",
    sourceUrl: "https://www.pexels.com/photo/san-diego-skyline-with-coronado-bridge-at-night-37026470/",
    photographer: "Soly Moses",
    photographerUrl: "https://www.pexels.com/@solyartphotos",
    license: "Pexels License",
    source: "Pexels",
    objectPosition: "center 35%",
    queryUsed: "Coronado Bridge San Diego",
    pexelsPhotoId: 37026470,
    reviewed: false,
  },
  "destin-30a": {
    src: "/images/destinations/destin-30a-hero.jpg",
    alt: "Golden sunrise over Destin Beach with charming seaside cottages and serene sands.",
    credit: "Esteban Carriazo",
    sourceUrl: "https://www.pexels.com/photo/scenic-sunrise-at-destin-beach-florida-32942419/",
    photographer: "Esteban Carriazo",
    photographerUrl: "https://www.pexels.com/@esteban-carriazo-2153373740",
    license: "Pexels License",
    source: "Pexels",
    objectPosition: "center 40%",
    queryUsed: "Destin Florida emerald coast",
    pexelsPhotoId: 32942419,
    reviewed: false,
  },
  "puerto-vallarta": {
    src: "/images/destinations/puerto-vallarta-hero.jpg",
    alt: "Beautiful beachfront with view of Puerto Vallarta city skyline and surrounding mountains.",
    credit: "Andrew Patrick Photo",
    sourceUrl: "https://www.pexels.com/photo/coastal-city-near-mountains-on-ocean-shore-27015582/",
    photographer: "Andrew Patrick Photo",
    photographerUrl: "https://www.pexels.com/@am83",
    license: "Pexels License",
    source: "Pexels",
    objectPosition: "center 35%",
    queryUsed: "Puerto Vallarta Malecon waterfront",
    pexelsPhotoId: 27015582,
    reviewed: false,
  },
  "puerto-escondido": {
    src: "/images/destinations/puerto-escondido-hero.jpg",
    alt: "Explore the rugged coastline with rocks and waves at Puerto Escondido, Mexico.",
    credit: "Dante Muñoz",
    sourceUrl: "https://www.pexels.com/photo/a-beach-with-rocks-and-water-in-the-background-15941841/",
    photographer: "Dante Muñoz",
    photographerUrl: "https://www.pexels.com/@dantemunozphoto",
    license: "Pexels License",
    source: "Pexels",
    objectPosition: "center 40%",
    queryUsed: "Puerto Escondido beach Oaxaca",
    pexelsPhotoId: 15941841,
    reviewed: false,
  },
  phuket: {
    src: "/images/destinations/phuket-hero.jpg",
    alt: "Explore the stunning landscape of Phang Nga Bay from a lush green viewpoint in Phuket, Thailand.",
    credit: "Yurix Sardinelly",
    sourceUrl: "https://www.pexels.com/photo/scenic-landscape-with-a-view-of-the-coast-16141088/",
    photographer: "Yurix Sardinelly",
    photographerUrl: "https://www.pexels.com/@yurix-sardinelly-504228832",
    license: "Pexels License",
    source: "Pexels",
    objectPosition: "center 40%",
    queryUsed: "Phang Nga Bay Thailand karst",
    pexelsPhotoId: 16141088,
    reviewed: false,
  },
  maldives: {
    src: "/images/destinations/maldives-hero.jpg",
    alt: "A breathtaking aerial view of overwater bungalows and pristine beaches in Kaafu Atoll, Maldives.",
    credit: "Asad Photo Maldives",
    sourceUrl: "https://www.pexels.com/photo/aerial-view-of-body-of-water-9215858/",
    photographer: "Asad Photo Maldives",
    photographerUrl: "https://www.pexels.com/@asadphoto",
    license: "Pexels License",
    source: "Pexels",
    objectPosition: "center 35%",
    queryUsed: "Maldives overwater bungalows aerial",
    pexelsPhotoId: 9215858,
    reviewed: false,
  },
  bali: {
    src: "/images/destinations/bali-hero.jpg",
    alt: "Stunning aerial view of Tegallalang Rice Terraces in Ubud, Bali, showcasing lush greenery and traditional huts.",
    credit: "Tom Fisk",
    sourceUrl: "https://www.pexels.com/photo/aerial-view-of-tegallalang-rice-terraces-bali-36716820/",
    photographer: "Tom Fisk",
    photographerUrl: "https://www.pexels.com/@tomfisk",
    license: "Pexels License",
    source: "Pexels",
    objectPosition: "center 35%",
    queryUsed: "Bali rice terraces Tegallalang",
    pexelsPhotoId: 36716820,
    reviewed: false,
  },
  "koh-samui": {
    src: "/images/destinations/koh-samui-hero.jpg",
    alt: "Explore the stunning coastal view of Koh Samui with lush greenery and bright blue sea.",
    credit: "foad niestat",
    sourceUrl: "https://www.pexels.com/photo/scenic-koh-samui-coastline-in-thailand-30852253/",
    photographer: "foad niestat",
    photographerUrl: "https://www.pexels.com/@foad-niestat-2645615",
    license: "Pexels License",
    source: "Pexels",
    objectPosition: "center 40%",
    queryUsed: "Koh Samui Thailand aerial",
    pexelsPhotoId: 30852253,
    reviewed: false,
  },
  "dubai-private": {
    src: "/images/destinations/dubai-private-hero.jpg",
    alt: "Stunning view of Dubai's skyline at twilight featuring the iconic Burj Khalifa.",
    credit: "Dreamer  Dude",
    sourceUrl: "https://www.pexels.com/photo/outstanding-cityscape-of-dubai-across-sea-at-dusk-18341554/",
    photographer: "Dreamer  Dude",
    photographerUrl: "https://www.pexels.com/@dreamer-dude-724231353",
    license: "Pexels License",
    source: "Pexels",
    objectPosition: "center 35%",
    queryUsed: "Dubai skyline Burj Khalifa",
    pexelsPhotoId: 18341554,
    reviewed: false,
  },
  "punta-del-este": {
    src: "/images/destinations/punta-del-este-hero.jpg",
    alt: "A serene sunset view over Punta del Este beach, capturing the natural beauty of Uruguay's coastline.",
    credit: "Pedro  Slinger",
    sourceUrl: "https://www.pexels.com/photo/city-buildings-near-the-shore-11838869/",
    photographer: "Pedro  Slinger",
    photographerUrl: "https://www.pexels.com/@pedrosk",
    license: "Pexels License",
    source: "Pexels",
    objectPosition: "center 40%",
    queryUsed: "Punta del Este La Mano sculpture",
    pexelsPhotoId: 11838869,
    reviewed: false,
  },
  marrakech: {
    src: "/images/destinations/marrakech-hero.jpg",
    alt: "A bustling scene at Jemaa el-Fnaa square in Marrakech with local snake charmers and tourists",
    credit: "Diego F. Parra",
    sourceUrl: "https://www.pexels.com/photo/jemaa-el-fnaa-square-in-marrakech-25489943/",
    photographer: "Diego F. Parra",
    photographerUrl: "https://www.pexels.com/@diego-f-parra-33199",
    license: "Pexels License",
    source: "Pexels",
    objectPosition: "center center",
    queryUsed: "Marrakech medina aerial",
    pexelsPhotoId: 25489943,
    reviewed: false,
  },
};
