export const SHADOW_DESTINATIONS = [
  {
    id: 'las-vegas',
    name: 'Las Vegas',
    region: 'Nevada',
    icao: ['KHND'],
    batch: 1,
    tracking_mode: 'shadow',
    short_description: 'Desert entertainment capital where private flyers stage for shows, conventions, and high-stakes weekends.',
    why_watch: 'Henderson Executive draws heavy same-market repositioning that can mask true long-haul private demand.',
    review_profile: 'local_loop_risk',
  },
  {
    id: 'vail-beaver-creek',
    name: 'Vail / Beaver Creek',
    region: 'Colorado Rockies',
    icao: ['KEGE'],
    batch: 1,
    tracking_mode: 'shadow',
    short_description: 'Alpine village skiing with upscale lodges, summer hiking, and a walkable mountain-town core.',
    why_watch: 'Eagle County traffic often includes Denver and Front Range shuttles alongside true destination ski-week arrivals.',
    review_profile: 'local_loop_risk',
  },
  {
    id: 'telluride',
    name: 'Telluride',
    region: 'Colorado Rockies',
    icao: ['KTEX'],
    batch: 1,
    tracking_mode: 'shadow',
    short_description: 'Remote box canyon resort with challenging terrain, festival culture, and dramatic San Juan scenery.',
    why_watch: 'A single high-elevation field with limited commercial overlap makes GA arrivals a relatively clean demand read.',
    review_profile: 'standard',
  },
  {
    id: 'big-sky-bozeman',
    name: 'Big Sky / Bozeman',
    region: 'Montana',
    icao: ['KBZN'],
    batch: 1,
    tracking_mode: 'shadow',
    short_description: 'Yellowstone gateway pairing ranch-country charm with Big Sky\'s expansive slopes and summer trails.',
    why_watch: 'Bozeman Yellowstone International mixes resort-bound jets with Montana repositioning and training traffic.',
    review_profile: 'local_loop_risk',
  },
  {
    id: 'lake-tahoe-truckee',
    name: 'Lake Tahoe / Truckee',
    region: 'California / Nevada',
    icao: ['KTRK'],
    batch: 1,
    tracking_mode: 'shadow',
    short_description: 'Sierra lake destination for skiing, boating, and cabin retreats within reach of Bay Area wealth.',
    why_watch: 'Truckee-Tahoe sees frequent Bay Area and Reno loops that can inflate apparent destination volume.',
    review_profile: 'local_loop_risk',
  },
  {
    id: 'carmel-monterey',
    name: 'Carmel / Monterey',
    region: 'California',
    icao: ['KMRY'],
    batch: 1,
    tracking_mode: 'shadow',
    short_description: 'Coastal California escape with Pebble Beach golf, aquarium visits, and art-gallery village strolls.',
    why_watch: 'Monterey Peninsula leisure traffic tends to arrive from distinct coastal and transcontinental origins.',
    review_profile: 'standard',
  },
  {
    id: 'key-west',
    name: 'Key West',
    region: 'Florida Keys',
    icao: ['KEYW'],
    batch: 1,
    tracking_mode: 'shadow',
    short_description: 'Southernmost island town with reef snorkeling, sunset sails, and a laid-back Old Town rhythm.',
    why_watch: 'End-of-the-road Keys leisure draws identifiable Florida and East Coast private flyers on long weekends.',
    review_profile: 'standard',
  },
  {
    id: 'bar-harbor-acadia',
    name: 'Bar Harbor / Acadia',
    region: 'Maine',
    icao: ['KBHB'],
    batch: 1,
    tracking_mode: 'shadow',
    short_description: 'Acadia National Park gateway with coastal hiking, lobster harbors, and crisp New England summers.',
    why_watch: 'Seasonal park and cruise-adjacent demand produces a readable summer private-travel pulse.',
    review_profile: 'standard',
  },
  {
    id: 'newport-rhode-island',
    name: 'Newport',
    region: 'Rhode Island',
    icao: ['KUUU'],
    batch: 1,
    tracking_mode: 'shadow',
    short_description: 'Gilded Age mansions, sailing regattas, and a compact harbor town on Narragansett Bay.',
    why_watch: 'Northeast yacht-week and summer-home traffic often includes short Boston and Providence repositioning hops.',
    review_profile: 'local_loop_risk',
  },
  {
    id: 'crete-chania',
    name: 'Crete / Chania',
    region: 'Greece',
    icao: ['LGSA'],
    batch: 1,
    tracking_mode: 'shadow',
    short_description: 'Western Crete gateway to Venetian harbors, gorge hikes, and relaxed island beach towns.',
    why_watch: 'Crete\'s busy western field mixes charter, scheduled, and private traffic on a single apron footprint.',
    review_profile: 'mixed_operations_risk',
  },
  {
    id: 'queenstown',
    name: 'Queenstown',
    region: 'New Zealand',
    icao: ['NZQN'],
    batch: 1,
    tracking_mode: 'shadow',
    short_description: 'Adventure capital framed by Remarkables peaks, vineyard valleys, and year-round outdoor thrills.',
    why_watch: 'Domestic Auckland and Christchurch shuttles frequently overlap with true international ski-holiday arrivals.',
    review_profile: 'local_loop_risk',
  },
  {
    id: 'langkawi',
    name: 'Langkawi',
    region: 'Malaysia',
    icao: ['WMKL'],
    batch: 1,
    tracking_mode: 'shadow',
    short_description: 'Duty-free archipelago of mangrove tours, beach resorts, and cable-car mountain views.',
    why_watch: 'A regional leisure field with modest GA volume may need extended screening before trends emerge.',
    review_profile: 'coverage_watch',
  },
];
