export const SHADOW_DESTINATIONS = [
  {
    id: 'grand-cayman',
    name: 'Grand Cayman',
    region: 'Cayman Islands',
    icao: ['MWCR'],
    batch: 1,
    tracking_mode: 'shadow',
  },
  {
    id: 'las-vegas',
    name: 'Las Vegas',
    region: 'Nevada',
    icao: ['KHND'],
    batch: 1,
    tracking_mode: 'shadow',
  },
  {
    id: 'vail-beaver-creek',
    name: 'Vail / Beaver Creek',
    region: 'Colorado Rockies',
    icao: ['KEGE'],
    batch: 1,
    tracking_mode: 'shadow',
  },
  {
    id: 'telluride',
    name: 'Telluride',
    region: 'Colorado Rockies',
    icao: ['KTEX'],
    batch: 1,
    tracking_mode: 'shadow',
  },
  {
    id: 'big-sky-bozeman',
    name: 'Big Sky / Bozeman',
    region: 'Montana',
    icao: ['KBZN'],
    batch: 1,
    tracking_mode: 'shadow',
  },
  {
    id: 'lake-tahoe-truckee',
    name: 'Lake Tahoe / Truckee',
    region: 'California / Nevada',
    icao: ['KTRK'],
    batch: 1,
    tracking_mode: 'shadow',
  },
  {
    id: 'carmel-monterey',
    name: 'Carmel / Monterey',
    region: 'California',
    icao: ['KMRY'],
    batch: 1,
    tracking_mode: 'shadow',
  },
  {
    id: 'key-west',
    name: 'Key West',
    region: 'Florida Keys',
    icao: ['KEYW'],
    batch: 1,
    tracking_mode: 'shadow',
  },
  {
    id: 'bar-harbor-acadia',
    name: 'Bar Harbor / Acadia',
    region: 'Maine',
    icao: ['KBHB'],
    batch: 1,
    tracking_mode: 'shadow',
  },
  {
    id: 'newport-rhode-island',
    name: 'Newport',
    region: 'Rhode Island',
    icao: ['KUUU'],
    batch: 1,
    tracking_mode: 'shadow',
  },
  {
    id: 'split-hvar',
    name: 'Split & Hvar',
    region: 'Croatia',
    icao: ['LDSP'],
    batch: 1,
    tracking_mode: 'shadow',
  },
  {
    id: 'dubrovnik',
    name: 'Dubrovnik',
    region: 'Croatia',
    icao: ['LDDU'],
    batch: 1,
    tracking_mode: 'shadow',
  },
  {
    id: 'crete-chania',
    name: 'Crete / Chania',
    region: 'Greece',
    icao: ['LGSA'],
    batch: 1,
    tracking_mode: 'shadow',
  },
  {
    id: 'paros',
    name: 'Páros',
    region: 'Greek Islands',
    icao: ['LGPA'],
    batch: 1,
    tracking_mode: 'shadow',
  },
  {
    id: 'corfu',
    name: 'Corfu',
    region: 'Greek Islands',
    icao: ['LGKR'],
    batch: 1,
    tracking_mode: 'shadow',
  },
  {
    id: 'menorca',
    name: 'Menorca',
    region: 'Balearic Islands',
    icao: ['LEMH'],
    batch: 1,
    tracking_mode: 'shadow',
  },
  {
    id: 'corsica-figari',
    name: 'Corsica / Figari',
    region: 'Corsica',
    icao: ['LFKF'],
    batch: 1,
    tracking_mode: 'shadow',
  },
  {
    id: 'puglia-brindisi',
    name: 'Puglia / Brindisi',
    region: 'Southern Italy',
    icao: ['LIBR'],
    batch: 1,
    tracking_mode: 'shadow',
  },
  {
    id: 'queenstown',
    name: 'Queenstown',
    region: 'New Zealand',
    icao: ['NZQN'],
    batch: 1,
    tracking_mode: 'shadow',
  },
  {
    id: 'langkawi',
    name: 'Langkawi',
    region: 'Malaysia',
    icao: ['WMKL'],
    batch: 1,
    tracking_mode: 'shadow',
  },
];
